---
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - ifElseChain
      - unnamedResult
  gocyclo:
    min-complexity: 15
  godot:
    exclude:
      - ^\s*\+
  govet:
    enable:
      - fieldalignment
  lll:
    line-length: 140
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wrapcheck
issues:
  exclude-rules:
    # Ignore long line and variable name non-compliance warnings in auto-generated file
    - linters:
        - lll
        - stylecheck
      path: "pkg/subctl/operator/common/embeddedyamls/yamls.go"
    # BrokerK8sApiServer parameter is used by other projects, like ACM,
    # so not changing it to BrokerK8sAPIServer as suggested by stylecheck
    - linters:
        - revive
        - stylecheck
      text: "struct field BrokerK8sApiServer"
    - path: .
      text: "ST1003: struct field NatEnabled"
    # Temporary, until https://github.com/submariner-io/submariner-operator/issues/1236
    # is addressed (sigs.k8s.io/controller-runtime/pkg/client/fake is deprecated)
    - path: controllers/servicediscovery/servicediscovery_controller_test.go
      text: "SA1019: package sigs.k8s.io/controller-runtime/pkg/client/fake is deprecated"
    - path: controllers/submariner/submariner_controller_test.go
      text: "SA1019: package sigs.k8s.io/controller-runtime/pkg/client/fake is deprecated"

    # Ignore pointer bytes in struct alignment tests (this is a very
    # minor optimisation)
    - linters:
        - govet
      text: "pointer bytes could be"
