---
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      # - performance
      - style
    disabled-checks:
      - ifElseChain
      - unnamedResult
      - unnecessaryDefer
  gocyclo:
    min-complexity: 20
  lll:
    line-length: 140
  maligned:
    suggest-new: true
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    # - dupl
    - errcheck
    - exportloopref
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    - lll
    - misspell
    - maligned
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    # - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
issues:
  exclude-rules:
    # Ignore long line and variable name non-compliance warnings in auto-generated file
    - linters:
        - lll
        - stylecheck
      path: "pkg/subctl/operator/common/embeddedyamls/yamls.go"

    # BrokerK8sApiServer parameter is used by other projects, like ACM,
    # so not changing it to BrokerK8sAPIServer as suggested by stylecheck
    - linters:
        - stylecheck
      text: "ST1003: struct field BrokerK8sApiServer"
