---
ignore:
  # No fix available for docker/docker
  - vulnerability: GHSA-pxq6-2prw-chj9
    package:
      name: github.com/docker/docker

  # No fix available
  - vulnerability: GHSA-rg2x-37c3-w2rh
    package:
      name: github.com/docker/docker

  # No fix available
  - vulnerability: GHSA-vp62-88p7-qqf5
    package:
      name: github.com/docker/docker

  # No fix available
  - vulnerability: GHSA-x86f-5xw2-fm2r
    package:
      name: github.com/docker/docker

  # No fix available
  - vulnerability: GO-2026-5932
    package:
      name: golang.org/x/crypto
  # No fix available for github.com/containerd/containerd.
  - vulnerability: GO-2026-5064
    package:
      name: github.com/containerd/containerd
      location: /tools/go.mod
  # No fix available for github.com/containerd/containerd.
  - vulnerability: GO-2026-5338
    package:
      name: github.com/containerd/containerd
      location: /tools/go.mod
  # No fix available for github.com/containerd/containerd.
  - vulnerability: GO-2026-5622
    package:
      name: github.com/containerd/containerd
      location: /tools/go.mod
  # No fix available for github.com/docker/docker.
  - vulnerability: GO-2026-4887
    package:
      name: github.com/docker/docker
      location: /tools/go.mod
