---
ignore:
  # False positive, CVE is actually about the C++ project protocolbuffers/protobuf
  # https://github.com/anchore/grype/issues/558
  - vulnerability: CVE-2015-5237
    package:
      name: google.golang.org/protobuf
  # False positive, CVE is actually about the C++ project protocolbuffers/protobuf
  # https://github.com/anchore/grype/issues/633
  - vulnerability: CVE-2021-22570
    package:
      name: google.golang.org/protobuf
  # Update requires K8s major version update. Low severity doesn't justify an update for stable branches.
  # https://github.com/submariner-io/shipyard/pull/1932#issuecomment-2830451046
  - vulnerability: GHSA-4hfp-h4cw-hj8p
    package:
      name: helm.sh/helm/v3
  - vulnerability: GHSA-5xqw-8hwv-wg92
    package:
      name: helm.sh/helm/v3
