---
ignore:
  # False positive, CVE is actually about the C++ project protocolbuffers/protobuf
  # https://github.com/anchore/grype/issues/558
  - vulnerability: CVE-2015-5237
    package:
      name: google.golang.org/protobuf
  # False positive, CVE is actually about the C++ project protocolbuffers/protobuf
  # https://github.com/anchore/grype/issues/633
  - vulnerability: CVE-2021-22570
    package:
      name: google.golang.org/protobuf
  # Fixing this CVE requires updating K8s et al to incompatible versions.
  - vulnerability: GHSA-r53h-jv2g-vpx6
    package:
      name: helm.sh/helm/v3
  - vulnerability: GHSA-v53g-5gjp-272r
    package:
      name: helm.sh/helm/v3
