---
extends: default

rules:
  line-length:
    max: 140
  # Allow standard GHA syntax for "on: *"
  truthy:
    ignore: '.github/workflows/*.yml'

ignore: |
  /vendor
  /deploy/submariner/crds/submariner.io_gateways.yaml
  /deploy/submariner/crds/submariner.io_endpoints.yaml
  /deploy/submariner/crds/submariner.io_clusters.yaml
  /deploy/crds/submariner.io_submariners.yaml
  /deploy/crds/submariner.io_servicediscoveries.yaml
  /deploy/lighthouse/crds/lighthouse.submariner.io_serviceimports.yaml
  /deploy/lighthouse/crds/lighthouse.submariner.io_serviceexports.yaml
  /deploy/lighthouse/crds/lighthouse.submariner.io_multiclusterservices.yaml
  /deploy/mcsapi/crds/multicluster.x_k8s.io_serviceexports.yaml
  /deploy/mcsapi/crds/multicluster.x_k8s.io_serviceimports.yaml

strict: true
