---
extends: default

rules:
  line-length:
    max: 140
  # Allow standard GHA syntax for "on: *"
  truthy:
    ignore: '.github/workflows/*.yml'

ignore: |
  /vendor
  /deploy/crds
  /deploy/submariner/crds
  /deploy/mcsapi/crds/multicluster.x_k8s.io_serviceexports.yaml
  /deploy/mcsapi/crds/multicluster.x_k8s.io_serviceimports.yaml
  /config/crd/bases/submariner.io_brokers.yaml
  /config/crd/bases/submariner.io_submariners.yaml
  /config/crd/bases/submariner.io_servicediscoveries.yaml
  /config/manager/kustomization.yaml
  /config/manifests/bases/submariner.clusterserviceversion.yaml
  /bundle
  /packagemanifests

strict: true
