---
extends: default

rules:
  line-length:
    max: 140
  # Allow standard GHA syntax for "on: *"
  truthy:
    ignore: '.github/workflows/*.yml'

ignore: |
  /vendor
  /deploy/crds/submariner.io_servicediscoveries_crd.yaml
  /deploy/crds/submariner.io_submariners_crd.yaml

strict: true
