---
resources:
  - manager.yaml

vars:
  - fieldref:
      fieldPath: metadata.namespace
    name: SUBMARINER_OPERATOR_NAMESPACE
    objref:
      group: apps
      kind: Deployment
      name: submariner-operator
      version: v1
