---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: submariner-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: submariner-operator
  namespace: system
  labels:
    control-plane: submariner-operator
spec:
  selector:
    matchLabels:
      control-plane: submariner-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: submariner-operator
    spec:
      serviceAccountName: submariner-operator
      containers:
        - name: submariner-operator
          # Replace this with the built image name
          image: controller:0.0.0
          command:
            - submariner-operator
          # args:
          #  - --enable-leader-election
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "submariner-operator"
