apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: ocp-submariner-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocp-submariner-gateway
subjects:
- kind: ServiceAccount
  name: submariner-gateway
  namespace: submariner-operator
