apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: ocp-submariner-routeagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocp-submariner-routeagent
subjects:
- kind: ServiceAccount
  name: submariner-routeagent
  namespace: submariner-operator
