apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: submariner-globalnet
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - submariner.io
  resources:
  - endpoints
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - submariner.io
  resources:
  - clusterglobalegressips
  - globalegressips
  - globalingressips
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - deletecollection
- apiGroups:
  - multicluster.x-k8s.io
  resources:
  - serviceexports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.openshift.io
  resources:
  - service/externalips
  verbs:
  - create
  - get
  - list
  - delete
