apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: submariner-diagnose
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submariner-diagnose
subjects:
- kind: ServiceAccount
  name: submariner-diagnose
  namespace: submariner-operator
