---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: submariner-diagnose
rules:
  # submariner-diagnose runs subctl diagnose to troubleshoot submariner
  # dpeloyment
  - apiGroups:  # nodes are looked up to figure out network settings
      - ""
    resources:
      - configmaps
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - submariner.io
    resources:
      - clusterglobalegressips
      - globalegressips
    verbs:
      - list
  - apiGroups:
      - multicluster.x-k8s.io
    resources:
      - "serviceexports"
    verbs:
      - list
