---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: submariner-diagnose
subjects:
  - kind: ServiceAccount
    name: submariner-diagnose
roleRef:
  kind: Role
  name: submariner-diagnose
  apiGroup: rbac.authorization.k8s.io
