---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: submariner-diagnose
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - create
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - submariner.io
    resources:
      - '*'
    verbs:
      - get
      - list
