---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocp-submariner-lighthouse-coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocp-submariner-lighthouse-coredns
subjects:
  - kind: ServiceAccount
    name: submariner-lighthouse-coredns
    namespace: placeholder
