apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kubefed-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - create
  - watch
  - list
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - create
  - watch
  - list
  - update
- apiGroups:
  - scheduling.kubefed.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - update
- apiGroups:
  - multiclusterdns.kubefed.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - delete
- apiGroups:
  - core.kubefed.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - create
  - update
- apiGroups:
  - types.kubefed.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - update
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - get
  - create
  - update
  - patch
