apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceimports.lighthouse.submariner.io
spec:
  group: lighthouse.submariner.io
  version: v2alpha1
  names:
    kind: ServiceImport
    plural: serviceimports
    singular: serviceimport
  scope: Namespaced
