---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: submariner-networkplugin-syncer
subjects:
  - kind: ServiceAccount
    name: submariner-networkplugin-syncer
roleRef:
  kind: ClusterRole
  name: submariner-networkplugin-syncer
  apiGroup: rbac.authorization.k8s.io
