apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: submariner-anonymous
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submariner-anonymous
