---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: submariner-gateway
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
secrets:
  - name: submariner-broker-secret
  - name: submariner-ipsec-psk
