---
- op: replace
  path: /spec/customresourcedefinitions/owned/0
  value:
    displayName: Broker
    description: Broker is the Schema for the brokers API
    kind: Broker
    name: brokers.submariner.io
    version: v1alpha1
    resources:
      - name: 'submariner-operator'
        kind: Deployment
    specDescriptors:
      - description: 'List of the components to be installed - any of [service-discovery, connectivity]'
        displayName: Components
        path: components
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Default cluster size for GlobalCIDR allocated to each cluster (amount of global IPs)'
        displayName: Default Globalnet Cluster Size
        path: defaultGlobalnetClusterSize
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:number
          - urn:alm:descriptor:com.tectonic.ui:fieldDependency:globalnetEnabled:true
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'Enable support for Overlapping CIDRs in connecting clusters'
        displayName: Enable Globalnet
        path: globalnetEnabled
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: 'GlobalCIDR supernet range for allocating GlobalCIDRs to each cluster'
        displayName: Globalnet CIDR Range
        path: globalnetCIDRRange
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
          - urn:alm:descriptor:com.tectonic.ui:fieldDependency:globalnetEnabled:true
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'List of domains to use for multi-cluster service discovery'
        displayName: Default Custom Domains
        path: defaultCustomDomains
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
          - urn:alm:descriptor:com.tectonic.ui:advanced
    statusDescriptors:
      - description: The observed state of the Broker
        displayName: Broker Status
        path: BrokerStatus
