---
- op: add
  path: /spec/customresourcedefinitions/owned/2/displayName
  value: Lighthouse
- op: add
  path: /spec/customresourcedefinitions/owned/2/description
  value: ServiceDiscovery is the Schema for the servicediscoveries API
