---
- op: replace
  path: /spec/customresourcedefinitions/owned/1
  value:
    displayName: Submariner
    description: Submariner is the Schema for the submariners API
    kind: Submariner
    name: submariners.submariner.io
    version: v1alpha1
    resources:
      - name: 'submariner-operator'
        kind: Deployment
    specDescriptors:
      - description: 'The broker namespace'
        displayName: Broker Remote Namespace
        path: brokerK8sRemoteNamespace
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'The service CIDR'
        displayName: Service CIDR
        path: serviceCIDR
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'The cluster CIDR'
        displayName: Cluster CIDR
        path: clusterCIDR
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'The Global CIDR super-net range for allocating GlobalCIDRs to each cluster'
        displayName: Global CIDR
        path: globalCIDR
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'The cluster ID used to identify the tunnels.'
        displayName: Cluster ID
        path: clusterID
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Cable driver implementation - any of [libreswan, wireguard, vxlan]'
        displayName: Cable Driver
        path: cableDriver
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:select:libreswan
          - urn:alm:descriptor:com.tectonic.ui:select:wireguard
          - urn:alm:descriptor:com.tectonic.ui:select:vxlan
      - description: 'Enable support for Service Discovery (lighthouse)'
        displayName: Enable Service Discovery
        path: serviceDiscoveryEnabled
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: 'Enable operator debugging'
        displayName: Debug
        path: debug
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'Enable logging IPsec debugging information'
        displayName: IPSec Debug
        path: ceIPSecDebug
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'This must be "k8s"'
        displayName: Broker
        path: broker
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'The broker API URL'
        displayName: Broker API Server
        path: brokerK8sApiServer
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'The broker API Token'
        displayName: Broker API Token
        path: brokerK8sApiServerToken
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:password
      - description: 'The broker certificate authority'
        displayName: Broker API CA
        path: brokerK8sCA
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:password
      - description: 'The namespace in which to deploy the submariner operator'
        displayName: Namespace
        path: namespace
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Enable automatic Load Balancer in front of the gateways'
        displayName: Enable Load Balancer
        path: loadBalancerEnabled
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: 'Enable NAT between clusters'
        displayName: Enable NAT
        path: natEnabled
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: 'The IPsec NAT traversal port (4500 usually)'
        displayName: IPSec NATT Port
        path: ceIPSecNATTPort
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:number
          - urn:alm:descriptor:com.tectonic.ui:fieldDependency:natEnabled:true
      - description: 'The IPsec IKE port (500 usually)'
        displayName: IPSec IKE Port
        path: ceIPSecIKEPort
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:number
      - description: 'The IPsec Pre-Shared Key which must be identical in all route agents across the cluster'
        displayName: IPSec Pre Shared Key
        path: ceIPSecPSK
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:password
      - description: 'Enable this cluster as a preferred server for data-plane connections'
        displayName: IPSec Preferred Server
        path: ceIPSecPreferredServer
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'Force UDP encapsulation for IPSec'
        displayName: IPSec Force UDP Encapsulation
        path: ceIPSecForceUDPEncaps
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'The image repository'
        displayName: Repository
        path: repository
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'The image tag'
        displayName: Version
        path: version
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:text
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'The gateway connection health check'
        displayName: Connection Health Check
        path: connectionHealthCheck
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'Enable the gateway health check'
        displayName: Enable The Connection Health Check
        path: connectionHealthCheck.enabled
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: 'Define the gateway health check Interval in seconds'
        displayName: Connection Health Check Interval
        path: connectionHealthCheck.intervalSeconds
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:number
          - urn:alm:descriptor:com.tectonic.ui:fieldDependency:connectionHealthCheck.enabled:true
      - description: 'Define the gateway health check maximum packet loss count'
        displayName: Connection Health Check Max Packet Loss Count
        path: connectionHealthCheck.maxPacketLossCount
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:number
          - urn:alm:descriptor:com.tectonic.ui:fieldDependency:connectionHealthCheck.enabled:true
      - description: 'Override component images'
        displayName: Image Override
        path: ImageOverrides
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:hidden
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: >-
          Name of the custom CoreDNS configmap to configure forwarding to lighthouse.
          It should be in <namespace>/<name> format where <namespace> is optional and defaults to kube-system.
        displayName: Core DNS Custom Config
        path: coreDNSCustomConfig
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: 'List of domains to use for multi-cluster service discovery'
        displayName: Custom Domains
        path: customDomains
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:advanced
    statusDescriptors:
      - description: 'The current NAT status'
        displayName: NAT Enabled
        path: natEnabled
        x-descriptors:
          - urn:alm:descriptor:text
      - description: 'The current color codes'
        displayName: Color Codes
        path: colorCodes
        x-descriptors:
          - urn:alm:descriptor:text
      - description: 'The current cluster ID'
        displayName: Cluster ID
        path: clusterID
        x-descriptors:
          - urn:alm:descriptor:text
      - description: 'The current service CIDR'
        displayName: Service CIDR
        path: serviceCIDR
        x-descriptors:
          - urn:alm:descriptor:text
      - description: 'The current cluster CIDR'
        displayName: Cluster CIDR
        path: clusterCIDR
        x-descriptors:
          - urn:alm:descriptor:text
      - description: 'The current global CIDR'
        displayName: Global CIDR
        path: globalCIDR
        x-descriptors:
          - urn:alm:descriptor:text
      - description: 'The current network plugin'
        displayName: Network Plugin
        path: networkPlugin
        x-descriptors:
          - urn:alm:descriptor:text
      - description: 'The status for the gateway daemonSet'
        displayName: Gateway DaemonSet Status
        path: gatewayDaemonSetStatus
      - description: 'The status for the routeAgent daemonSet'
        displayName: RouteAgent DaemonSet Status
        path: routeAgentDaemonSetStatus
      - description: 'The status for the globalnet daemonSet'
        displayName: Globalnet DaemonSet Status
        path: globalnetDaemonSetStatus
      - description: 'The status for the load balancer'
        displayName: Load Balancer Status
        path: loadBalancerStatus
      - description: 'Summary of the submariner gateways in a cluster'
        displayName: Gateways
        path: gateways
      - description: 'Information about the deployment in a cluster'
        displayName: Deployment Info
        path: deploymentInfo
