---
- op: add
  path: /spec/customresourcedefinitions/owned/1/displayName
  value: Submariner
- op: add
  path: /spec/customresourcedefinitions/owned/1/description
  value: Submariner is the Schema for the submariners API
