---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-submariner-metrics
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
roleRef:
  kind: Role
  name: submariner-metrics-reader
  apiGroup: rbac.authorization.k8s.io
