apiVersion: apps/v1
kind: Deployment
metadata:
  name: submariner-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: submariner-operator
  template:
    metadata:
      labels:
        name: submariner-operator
    spec:
      serviceAccountName: submariner-operator
      containers:
        - name: submariner-operator
          # Replace this with the built image name
          image: quay.io/submariner/submariner-operator:0.1.0
          command:
          - submariner-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "submariner-operator"
