---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: submariner-operator
rules:
  - apiGroups:
      - ""
    resources:
      # For metrics
      - services
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - ""
    resources:
      # For syncing Secrets from the broker
      - secrets
    verbs:
      - get
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      # Temporarily needed for network-plugin syncer removal
      - serviceaccounts
    resourceNames:
      - submariner-networkplugin-syncer
    verbs:
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      # Needed for openshift monitoring
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - submariner-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - submariner.io
    resources:
      - brokers
      - brokers/status
      - submariners
      - submariners/status
      - servicediscoveries
      - servicediscoveries/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - submariner.io
    resources:
      - gateways
    verbs:
      - get
      - list
      - watch
