apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patches/submariner.csv.config.yaml
  target:
    group: operators.coreos.com
    kind: ClusterServiceVersion
    name: submariner.v0.20.2
    namespace: placeholder
    version: v1alpha1
commonAnnotations:
  createdAt: "2026-02-05 13:34:06"
  features.operators.openshift.io/disconnected: "true"
  features.operators.openshift.io/fips-compliant: "true"
  features.operators.openshift.io/proxy-aware: "false"
  features.operators.openshift.io/tls-profiles: "false"
  features.operators.openshift.io/token-auth-aws: "false"
  features.operators.openshift.io/token-auth-azure: "false"
  features.operators.openshift.io/token-auth-gcp: "false"
  operators.openshift.io/valid-subscription: '["OpenShift Platform Plus", "Red Hat
    Advanced Cluster Management for Kubernetes"]'
resources:
- ../../bundle/manifests/submariner.clusterserviceversion.yaml
