---
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-operator
    value: registry.redhat.io/rhacm2/submariner-rhel9-operator@sha256:2ca7a48926011e9642b7044a8ca992f92509f84a4ec0b32de655eae7dbf512a5
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-gateway
    value: registry.redhat.io/rhacm2/submariner-gateway-rhel9@sha256:c0ebcbb012c524bb39ba5d73be0c6d0d483e074688b2fdf7dd5ec691c4e5fd5b
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-routeagent
    value: registry.redhat.io/rhacm2/submariner-route-agent-rhel9@sha256:b769899d2b2442c5f74af88fc223a205a43dd77c3eb3eb8c7d6cc94da0848711
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-globalnet
    value: registry.redhat.io/rhacm2/submariner-globalnet-rhel9@sha256:42b6b05540a7ad8532d7d5d116edac74b1de244683921341cf4eb492965e7f7d
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-lighthouse-agent
    value: registry.redhat.io/rhacm2/lighthouse-agent-rhel9@sha256:74f7b9db4452e1028b511e35897bfe069e2244ad873225f0335c8e56b16ba02d
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-lighthouse-coredns
    value: registry.redhat.io/rhacm2/lighthouse-coredns-rhel9@sha256:cf37d79608353b03cc93a70a7dc5a02ed3815a6085959212e2e56af96fd3bf73
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-nettest
    value: registry.redhat.io/rhacm2/nettest-rhel9@sha256:88becb4ea7df4143e13702a5853337a63efa16c5eea79598104844ece6c30bed
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-metrics-proxy
    value: registry.redhat.io/rhacm2/nettest-rhel9@sha256:88becb4ea7df4143e13702a5853337a63efa16c5eea79598104844ece6c30bed
- op: replace
  path: /spec/template/spec/containers/0/image
  value: registry.redhat.io/rhacm2/submariner-rhel9-operator@sha256:2ca7a48926011e9642b7044a8ca992f92509f84a4ec0b32de655eae7dbf512a5
