---
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-operator
    value: registry.redhat.io/rhacm2/submariner-rhel9-operator@sha256:2798452d47e3837e8bc938108fc3b4b024896b91f8ff816048caab6dd0e2dc4e
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-gateway
    value: registry.redhat.io/rhacm2/submariner-gateway-rhel9@sha256:1bf2533d79facf273e92327eebd0661591fc3d30a6ac4ce27c7913cafc3eb177
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-routeagent
    value: registry.redhat.io/rhacm2/submariner-route-agent-rhel9@sha256:17a1afb154dcb85ef8d7df186fff276f4f16ed8dea53e023ebba1059ab4ce575
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-globalnet
    value: registry.redhat.io/rhacm2/submariner-globalnet-rhel9@sha256:a675fa66f3b4e4e52737fc8575b582352158c1da353b3726c671f4be7c4b7a16
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-lighthouse-agent
    value: registry.redhat.io/rhacm2/lighthouse-agent-rhel9@sha256:46a18d4f7e224ab8c6b4ade98107434205396a79dee0c8d3925bc9b23f379c02
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-lighthouse-coredns
    value: registry.redhat.io/rhacm2/lighthouse-coredns-rhel9@sha256:de4b0dacc8e26b6c0e018144e2a79cf9688545353b170603491c2bbc4fdafa3d
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-metrics-proxy
    value: registry.redhat.io/rhacm2/nettest-rhel9@sha256:53ac9dcc2e71806b7d63178cef6a4eb0d8a343e38fd725b679351af992127faf
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_submariner-nettest
    value: registry.redhat.io/rhacm2/nettest-rhel9@sha256:53ac9dcc2e71806b7d63178cef6a4eb0d8a343e38fd725b679351af992127faf
- op: replace
  path: /spec/template/spec/containers/0/image
  value: registry.redhat.io/rhacm2/submariner-rhel9-operator@sha256:2798452d47e3837e8bc938108fc3b4b024896b91f8ff816048caab6dd0e2dc4e
