---
namespace: submariner-k8s-broker

resources:
  - namespace.yaml
  - broker-admin/service_account.yaml
  - broker-admin/role.yaml
  - broker-admin/role_binding.yaml
  - broker-client/service_account.yaml
  - broker-client/role.yaml
  - broker-client/role_binding.yaml

#vars:
#  - name: SUBMARINER_BROKER_NAMESPACE
#    objref:
#      kind: Namespace
#      version: v1
#      name: submariner-k8s-broker
#    fieldref:
#      fieldpath: metadata.name

configurations:
  - kustomizeconfig.yaml
