---
# the following config is for teaching kustomize where to look at when substituting vars.
# It requires kustomize v2.1.0 or newer to work properly.

namespace:
  - path: metadata/namespace
    create: true
  - kind: ClusterRoleBinding
    group: rbac.authorization.k8s.io
    version: v1
    path: subjects/namespace
    create: true
  - kind: RoleBinding
    group: rbac.authorization.k8s.io
    version: v1
    path: subjects/namespace
    create: true
