#!/bin/bash
set -e

source $(dirname $0)/lib/debug_functions
source $(dirname $0)/lib/version

debug=${1:-false}

cd $(dirname $0)/..
mkdir -p bin
echo Building subctl version $VERSION for ${GOOS:=$(go env GOOS)}/${GOARCH:=$(go env GOARCH)}
ldflags="-X main.VERSION=$VERSION"
if [ "$debug" = "false" ]; then
    ldflags="-s -w ${ldflags}"
fi
output=bin/subctl-${VERSION}-${GOOS}-${GOARCH}${GOEXE}
CGO_ENABLED=0 go build -ldflags "${ldflags}" -o ${output} ./pkg/subctl/main.go
[ "$debug" = "false" ] && command -v upx > /dev/null && upx ${output} || :

if [ "${GOARCH}" = "$(GOARCH= go env GOARCH)" ] && [ "${GOOS}" = "$(GOOS= go env GOOS)" ]; then
    ln -sf ${output#bin/} bin/subctl
fi
