#!/bin/bash
set -e

source ${SCRIPTS_DIR}/lib/debug_functions
source ${SCRIPTS_DIR}/lib/version

cd ${DAPPER_SOURCE}

PACK_SUBCTL="${PACK_SUBCTL:-false}"

echo Building subctl version $VERSION for ${GOOS:=$(go env GOOS)}/${GOARCH:=$(go env GOARCH)}
GIT_REF="$(git describe --tags)"
ldflags="-X github.com/submariner-io/submariner-operator/pkg/version.Version=${VERSION} "
ldflags="${ldflags} -X github.com/submariner-io/submariner-operator/pkg/version.GitRef=${GIT_REF}"

output=bin/subctl-${VERSION}-${GOOS}-${GOARCH}${GOEXE}

${SCRIPTS_DIR}/compile.sh --ldflags "$ldflags" --noupx $output ./pkg/subctl/main.go "$@"

if [ "${GOARCH}" = "$(GOARCH= go env GOARCH)" ] && [ "${GOOS}" = "$(GOOS= go env GOOS)" ]; then
    ln -sf ${output#bin/} bin/subctl
fi

if [ "${PACK_SUBCTL}" = "true" ]; then
  tar -cJf bin/subctl-${VERSION}-${GOOS}-${GOARCH}.tar.xz --transform "s/^bin/subctl-${VERSION}/" ${output}
fi
