#!/bin/bash
set -e

source $(dirname $0)/lib/debug_functions

cd $(dirname $0)

./generate-embeddedyamls

export PACK_SUBCTL=true

GOOS=linux GOARCH=amd64 ./build-subctl
GOOS=linux GOARCH=arm64 ./build-subctl
GOOS=darwin GOARCH=amd64 ./build-subctl
GOOS=windows GOARCH=amd64 ./build-subctl
