#!/bin/bash

source $(dirname $0)/lib/debug_functions
source $(dirname $0)/lib/version

cd $(dirname $0)/..

# embed the CRD yaml files into constants
go generate pkg/subctl/operator/common/embeddedyamls/generate.go

