#!/bin/bash
set -e

source $(dirname $0)/lib/debug_functions

cd $(dirname $0)/..

source scripts/lib/find_functions

PACKAGES="pkg/..."

echo Running tests in ${PACKAGES}
[ "${ARCH}" == "amd64" ] && RACE=-race
ginkgo ${RACE} -cover ${PACKAGES}
