package main

import (
	"fmt"
	"io"
	"os"
	"path"
	"strings"
)

const (
	yamlsDirectory = "../../../../../deploy"
)

var files = []string{
	"crds/submariner.io_submariners_crd.yaml",
	"operator.yaml",
	"role.yaml",
	"role_binding.yaml",
	"service_account.yaml",
}

// Reads all .yaml files in the crdDirectory
// and encodes them as constants in crdyamls.go
func main() {

	fmt.Println("Generating yamls.go")
	out, err := os.Create("yamls.go")
	panicOnErr(err)

	_, err = out.WriteString("// This file is auto-generated by yamls2go.go\n" +
		"package embeddedyamls\n\nconst (\n")
	panicOnErr(err)

	for _, f := range files {

		_, err = out.WriteString("\t" + constName(f) + " = `")
		panicOnErr(err)

		fmt.Println(f)
		f, _ := os.Open(path.Join(yamlsDirectory, f))
		_, err = io.Copy(out, f)
		panicOnErr(err)

		_, err = out.WriteString("`\n")
		panicOnErr(err)

	}
	_, err = out.WriteString(")\n")
	panicOnErr(err)

	err = out.Close()
	panicOnErr(err)
}

func panicOnErr(err error) {
	if err != nil {
		panic(err)
	}
}

func constName(filename string) string {
	return strings.Title(strings.Replace(
		strings.Replace(filename,
			".", "_", -1),
		"/", "_", -1))
}
