---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: submariner-routeagent-ovn
  namespace: openshift-ovn-kubernetes
subjects:
  - kind: ServiceAccount
    name: submariner-routeagent
roleRef:
  kind: ClusterRole
  name: submariner-routeagent-ovn
  apiGroup: rbac.authorization.k8s.io
