---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: submariner-routeagent-ovn
rules:
  - apiGroups:  # the route agent needs access to ovn secrets
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
