apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default
- ../samples
- ../scorecard

images:
- name: controller
  newName: quay.io/submariner/submariner-operator
  newTag: release-0.19-47a20cd423c1
- name: repo
  newName: quay.io/submariner
