ARG BASE_BRANCH
ARG SOURCE=/go/src/github.com/submariner-io/submariner-operator

FROM --platform=${BUILDPLATFORM} registry.redhat.io/ubi9/go-toolset:latest AS builder
ARG SOURCE
ARG TARGETPLATFORM

COPY . ${SOURCE}

USER root
RUN chown -R 1001:0 ${SOURCE}
USER 1001

RUN git config --global --add safe.directory ${SOURCE}

WORKDIR ${SOURCE}

RUN CGO_ENABLED=0 GOARCH=${TARGETPLATFORM##*/} go build \
    -v -o ${SOURCE}/bin/${TARGETPLATFORM}/submariner-operator \
    ${SOURCE}/cmd

#RUN make -C ${SOURCE} LOCAL_BUILD=1 bin/${TARGETPLATFORM}/submariner-operator

FROM --platform=${TARGETPLATFORM} registry.redhat.io/ubi9/ubi-minimal:latest
ARG BASE_BRANCH
ARG SOURCE
ARG SOURCE_DATE_EPOCH
ARG TARGETPLATFORM

ENV USER_UID=1001

# TODO Improve these labels
LABEL name="submariner-operator" \
      version="${BASE_BRANCH}" \
      release="${BASE_BRANCH}" \
      summary="Submariner Operator" \
      description="The Submariner Operator manages the lifecycle of Submariner components." \
      maintainer="multi-cluster-networking@redhat.com" \
      cpe="cpe:/a:redhat:submariner_operator:${BASE_BRANCH}::el9" \
      io.k8s.display-name="Submariner Operator" \
      io.k8s.description="The Submariner Operator manages the lifecycle of Submariner components." \
      org.opencontainers.image.vendor="Red Hat" \
      org.opencontainers.image.title="submariner-operator" \
      org.opencontainers.image.version="${BASE_BRANCH}" \
      org.opencontainers.image.revision="0" \
      org.opencontainers.image.created="${SOURCE_DATE_EPOCH}" \
      org.opencontainers.image.description="The Submariner Operator manages the lifecycle of Submariner components." \
      org.opencontainers.image.source="https://github.com/submariner-io/submariner-operator"

COPY --from=builder ${SOURCE}/bin/${TARGETPLATFORM}/submariner-operator /submariner-operator

RUN chown 1001:0 /submariner-operator && chmod 500 /submariner-operator

ENTRYPOINT ["/submariner-operator"]

USER ${USER_UID}
