ARG BASE_BRANCH=release-0.22
ARG SOURCE=/go/src/github.com/submariner-io/submariner-operator

FROM --platform=${BUILDPLATFORM} registry.redhat.io/ubi9/go-toolset:latest AS builder
ARG SOURCE
ARG TARGETPLATFORM
ARG BASE_BRANCH

ENV GOEXPERIMENT=strictfipsruntime
ARG BUILD_TAGS="strictfipsruntime"

COPY . ${SOURCE}

USER root
RUN chown -R 1001:0 ${SOURCE}
USER 1001

RUN git config --global --add safe.directory ${SOURCE}

WORKDIR ${SOURCE}

RUN mkdir -p bin && cd tools && go build -o ../bin/controller-gen sigs.k8s.io/controller-tools/cmd/controller-gen
RUN bin/controller-gen object:headerFile="hack/boilerplate.go.txt,year=$(date +"%Y")" paths="./..."
RUN bin/controller-gen crd:crdVersions=v1 paths="./..." output:crd:artifacts:config=deploy/crds
RUN bin/controller-gen crd:crdVersions=v1 paths="github.com/submariner-io/submariner/pkg/apis/..." output:crd:artifacts:config=deploy/submariner/crds

RUN CGO_ENABLED=1 GOARCH=${TARGETPLATFORM##*/} go build \
    -ldflags "-s -w \
    -X main.version=${BASE_BRANCH} \
    -X github.com/submariner-io/submariner-operator/api/v1alpha1.DefaultRepo=registry.redhat.io/rhacm2 \
    -X github.com/submariner-io/submariner-operator/api/v1alpha1.DefaultSubmarinerOperatorVersion=${BASE_BRANCH} \
    -X github.com/submariner-io/submariner-operator/api/v1alpha1.DefaultSubmarinerVersion=${BASE_BRANCH} \
    -X github.com/submariner-io/submariner-operator/api/v1alpha1.DefaultLighthouseVersion=${BASE_BRANCH} \
    -X github.com/submariner-io/submariner-operator/pkg/names.GatewayImage=submariner-gateway-rhel9 \
    -X github.com/submariner-io/submariner-operator/pkg/names.RouteAgentImage=submariner-route-agent-rhel9 \
    -X github.com/submariner-io/submariner-operator/pkg/names.GlobalnetImage=submariner-globalnet-rhel9 \
    -X github.com/submariner-io/submariner-operator/pkg/names.ServiceDiscoveryImage=lighthouse-agent-rhel9 \
    -X github.com/submariner-io/submariner-operator/pkg/names.LighthouseCoreDNSImage=lighthouse-coredns-rhel9 \
    -X github.com/submariner-io/submariner-operator/pkg/names.OperatorImage=submariner-rhel9-operator \
    -X github.com/submariner-io/submariner-operator/pkg/names.MetricsProxyImage=nettest-rhel9 \
    -X github.com/submariner-io/submariner-operator/pkg/names.NettestImage=nettest-rhel9" \
    -tags "${BUILD_TAGS}" \
    -v -o ${SOURCE}/bin/submariner-operator \
    ${SOURCE}/cmd

FROM --platform=${TARGETPLATFORM} registry.redhat.io/ubi9/ubi-minimal:latest
ARG BASE_BRANCH
ARG SOURCE
ARG SOURCE_DATE_EPOCH

RUN adduser -r -l -u 1001 -G root submariner

COPY --from=builder ${SOURCE}/bin/submariner-operator /usr/local/bin/submariner-operator

RUN chown -Rc submariner:root /usr/local/bin
RUN chmod -Rc 775 /usr/local/bin

COPY --from=builder ${SOURCE}/LICENSE /licenses/LICENSE

ENTRYPOINT ["/usr/local/bin/submariner-operator"]

USER submariner

LABEL com.redhat.component="submariner-operator-container" \
      name="rhacm2/submariner-rhel9-operator" \
      version="${BASE_BRANCH}" \
      summary="Submariner Operator" \
      description="The Submariner Operator manages the lifecycle of Submariner components." \
      io.k8s.display-name="Submariner Operator" \
      io.k8s.description="The Submariner Operator manages the lifecycle of Submariner components." \
      io.openshift.tags="submariner,submariner-operator,rhel9" \
      maintainer="multi-cluster-networking@redhat.com" \
      com.github.url="https://github.com/submariner-io/submariner-operator" \
      com.github.commit="${BASE_BRANCH}" \
      cpe="cpe:/a:redhat:acm:2.15::el9" \
      org.opencontainers.image.created="${SOURCE_DATE_EPOCH}"
