apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-controller
  namespace: kubefed-operator # use submariner namespace for production
  labels:
    app: lighthouse-controller
spec:
  selector:
    matchLabels:
      app: lighthouse-controller
  template:
    metadata:
      labels:
        app: lighthouse-controller
    spec:
      containers:
        - name: lighthouse-controller
          image: quay.io/submariner/lighthouse-controller:0.1.0
          command: ["lighthouse-controller"]
          args: ["--kubefed-namespace=kubefed-operator", "-v=4", "-alsologtostderr"]
      serviceAccount: kubdefed-operator     # for production we need to create our own service account and
      serviceAccountName: kubefed-operator # provide access to KubeFedClusters
