---
name: Cross-Build Checks

on:
  pull_request:

jobs:
  cross:
    name: Cross-Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Build all supported binaries
        run: make build-cross
