---
name: Cross-Build Checks

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize, converted_to_draft, labeled]

jobs:
  cross:
    name: Cross-Build
    if: github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'test-draft')
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748

      - name: Build all supported binaries
        run: make build-cross
