---
name: Release Subctl

on:
  release:
    types: [created]

jobs:
  release-subctl:
    name: Release Subctl
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0

      - name: Fetch all git tags
        run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Generate the subctl release artifacts
        run: make build-cross

      - name: Publish built artifacts to GitHub for release
        uses: skx/github-action-publish-binaries@c881a3f8ffb80b684f367660178d38ceabc065c2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'dist/*.tar.xz'
