---
name: Release Images

on:
  push:
    branches:
      - master
      - release-*

jobs:
  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Reclaim free space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile

      - name: Run E2E deployment and tests
        run: make e2e

      - name: Post mortem
        if: failure()
        run: make post-mortem

      - name: Clean up E2E deployment
        run: make cleanup

  release:
    name: Release Images
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build the Operator image
        env:
          IMAGES_ARGS: --nocache
        run: make operator-image

      - name: Release the Operator image
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        # Pass RELEASE_ARGS on the call, since GITHUB_REF set in the `env` directive doesn't get properly expanded
        run: make release RELEASE_ARGS="submariner-operator --tag '${GITHUB_REF##*/}'"
