on:
  push:
    branches:
      - master
    tags:
      - 'v**'

name: Release Images
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile

      - run: make e2e

      - name: Post Mortem
        if: failure()
        run: make post-mortem

      - run: make cleanup

  release:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Release the operator image
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          RELEASE_ARGS: submariner-operator
        run: |
          [[ $GITHUB_REF =~ "/tags/" ]] && RELEASE_ARGS+=" --tag ${GITHUB_REF##*/}"
          make build-operator release
