---
name: Release Subctl

on:
  release:
    types: [created]

jobs:
  release-subctl:
    name: Release Subctl
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all git tags
        run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Generate the subctl release artifacts
        run: make build-cross

      - name: Publish built artifacts to GitHub for release
        uses: skx/github-action-publish-binaries@release-0.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'dist/*.tar.xz'
