---
name: Reporting

on:
  push:
    branches:
      - release-0.15
      - release-*

permissions: {}

jobs:
  unit-coverage:
    name: Go Unit Test Coverage
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 0

      - name: Run Go unit tests
        run: make unit

      - name: Run SonarScan, upload Go test results and coverage
        uses: sonarsource/sonarcloud-github-action@cb201f3b2d7a38231a8c042dfea4539c8bea180b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  variant-analysis:
    name: Variant Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@f3feb00acb00f31a6f60280e6ace9ca31d91c76a
        with:
          languages: go
      - name: Run CodeQL variant analysis
        uses: github/codeql-action/analyze@f3feb00acb00f31a6f60280e6ace9ca31d91c76a
      - name: Show CodeQL scan SARIF report
        if: always()
        run: cat ../results/go.sarif

  vulnerability-scan:
    name: Vulnerability Scanning
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Run Anchore vulnerability scanner
        uses: anchore/scan-action@4be3c24559b430723e51858969965e163b196957
        id: scan
        with:
          path: "."
          fail-build: false
      - name: Show Anchore scan SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@f3feb00acb00f31a6f60280e6ace9ca31d91c76a
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
