---
name: Reporting

on:
  push:
    branches:
      - devel
      - release-*

permissions: {}

jobs:
  vulnerability-scan:
    name: Vulnerability Scanning
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Run Anchore vulnerability scanner
        uses: anchore/scan-action@ecfd0e98932e57ea8f68f29c4f418fc41a8194db
        id: scan
        with:
          path: "."
          fail-build: false
      - name: Show Anchore scan SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@b398f525a5587552e573b247ac661067fafa920b
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

  variant-analysis:
    name: Variant Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Initialize CodeQL
        uses: github/codeql-action/init@b398f525a5587552e573b247ac661067fafa920b
        with:
          languages: go
      - name: Build code, creating CodeQL database
        run: make build
      - name: Run CodeQL variant analysis
        uses: github/codeql-action/analyze@b398f525a5587552e573b247ac661067fafa920b
      - name: Show CodeQL scan SARIF report
        if: always()
        run: cat ../results/go.sarif
