---
on:
  push:
    branches:
      - devel
      - release-*

name: Release Subctl Devel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch origin +refs/tags/*:refs/tags/*

      - name: generate version tag
        run: echo "SUBCTL_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Generate the Artifacts
        run: |
          make build-cross VERSION=${{ env.SUBCTL_TAG }}
          echo "BINARIES=$(find dist/ -type f -name '*.tar.xz' -printf '%p ')" >> $GITHUB_ENV

      - name: Update the Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: "Cutting Edge: ${{ env.SUBCTL_TAG }}"
          tag: subctl-${{ env.SUBCTL_TAG }}
          files: ${{ env.BINARIES }}

      - name: Bump the subctl tag
        uses: richardsimko/update-tag@v1.0.3
        with:
          tag_name: subctl-${{ env.SUBCTL_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
