---
name: Unit Tests

on:
  pull_request:
  push:
    tags:
      - 'v**'

jobs:
  unit-testing:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Run Go unit tests
        run: |
          set -o pipefail
          make unit 2>&1 | tee artifacts/unittest.log

      - name: Collect artifacts
        run: |
          for f in $(find ./pkg -name "*.xml"); do
            mkdir -p artifacts/$(dirname $f)
            cp $f -rfp artifacts/$f
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: Unit test artifacts
          path: artifacts
